version: '3.8'

services:
  bot:
    build: .
    container_name: telegram_bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./bot.db:/app/bot.db  # сохраняем SQLite вне контейнера
